### ISSUE TITLE
Organization must be updated so it can be published independenty

### ISSUE THREAD

**Issue by cchantep** [osxhacker/ReactiveMongo-Criteria#4]
https://github.com/osxhacker/ReactiveMongo-Criteria/blob/edb4a24b646323f1805d82a4b95d5ad64ffdfeaf/project/Criteria.scala#L24

**Comment by osxhacker** [comment]
@cchantep,

I have never published this library because **you personally told me** that the driver did everything that this library provides.

Regarding the organization name, I refer you to what Stephane Godbillon wrote to me on 2014-05-06:

> I'll create before the end of the week a new Github project in the organization, called reactivemongo-dsl (if you have another name in mind, just tell me.)  I really prefer that the sources of the artifacts in the group org.reactivemongo are hosted in the same organization.  You would be the main maintainer of this project. 

> By the way, did you see Fehmi's work?  I think it would be nice to notice him first that an official DSL library will be added in the organization repository, and it would be great if we could work together on this project – what do you think?

> If you agree with that, let's include Fehmi in our discussion, and create the subrepository before Friday.

> Whatever you decide, thank you for your effort. It's really appreciated (even if I'm not very reactive these last days – no pun intended.) Actually, I need help to support ReactiveMongo and I'd be very happy to count you among the project maintainers.

Since **you** obviously have a problem with the unpublished library's organization name, and no one else as for almost seven (7) years, when I get a chance I shall refactor this project to not be directly related to "org.reactivemongo".

**Comment by cchantep** [comment]
Seriously ... you've just [mentioned this lib](https://groups.google.com/g/reactivemongo/c/m8QNAgkWVBs/m/pAIHfoyLAQAJ) on the mailing list.

Having such community lib aside the driver is fine and great for me.

But the org name is misleading. That's all. Understand it as you want.

Best regards.

**Comment by osxhacker** [comment]
I did mention it on the mailing list because I thought it could help the person.  No one has had an issue until now and the organization name was what Stephane told me to use.

As I said, I will disassociate the project from ReactiveMongo.

**Comment by osxhacker** [comment]
This project is the process of being archived. New work is now being done in [scala-bson-query](https://github.com/osxhacker/scala-bson-query)
